from abc import ABC

from app.adapters.schemas.user import UserCreateSchema
from app.infra.models.user import UserModel


class IUsersRepository(ABC):

    def register(self, data: UserCreateSchema) -> UserModel | None: ...
    def find (self, **kwargs) -> UserModel: ...
    def findall (self, **kwargs) -> list[UserModel]: ...
    def update (self, id: int, **kwargs): ...
    def delete (self, id: int): ...
